### PR TITLE
2.0.3

### LINKED ISSUE #23: License conflict for @adobe/aep-rules-engine having both Apache 2.0 and OSL-3.0 license files
### Expected Behaviour

Hi, 

Not sure if this is the right forum to request/ask this but let me know if it is not.

My organization is adopting the Adobe Web SDK, one of the paths we are exploring is consuming the Web SDK from its Open Source package: https://github.com/adobe/alloy as officially documented by Adobe, ref. https://experienceleague.adobe.com/en/docs/experience-platform/web-sdk/home.

We realized we cannot use this path due to a licensing issue that is in this `@adobe/aep-rules-engine` package which is a direct dependency of Alloy (see [Alloy's package.json file](https://github.com/adobe/alloy/blob/main/package.json#L74)). Specifically, my Legal org's team has identified there is a conflict between Apache 2.0 (which is allowlisted by my org to use it, see license file https://github.com/adobe/aepsdk-rulesengine-typescript/blob/main/LICENSE) and the OSL-3.0 file (see license file https://github.com/adobe/aepsdk-rulesengine-typescript/blob/main/COPYING.txt).

My specific questions are:
- Is it possible to distribute this package under the same Apache 2.0 license as done in the Alloy package?
- Are there any other packages in Adobe Open Source dependency tree using this mixed licensing model that we need to be aware of?

### Actual Behaviour
- Ideally, this `@adobe/aep-rules-engine` package should be distributed with the same Apache 2.0 license as the main Alloy package.

### Reproduce Scenario (including but not limited to)
N/A
#### Steps to Reproduce
N/A
#### Platform and Version
N/A

#### Sample Code that illustrates the problem
N/A
#### Logs taken while reproducing problem
N/A

Best regards.

### PR DESCRIPTION
**Pull request by carterworks**
## Description

Increase the version number to 2.0.3 

## Related Issue

https://jira.corp.adobe.com/browse/PLATIR-45664

## Motivation and Context

Release #24 to resolve #25 and closes #23

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by carterworks** [comment]
We are in a company-wide restricted change period until January 5th, so unless an exception is made, expect this to be released then.

**Comment by carterworks** [comment]
I will make sure to update the https://www.github.com/adobe/alloy library as well after this is released.

**Review by dompuiu — APPROVED** [review]

**Comment by alex-arriaga** [comment]
Hi @carterworks  thank you for making this version bump, do we have an estimate about how long it will take for us to see this new version on NPM https://www.npmjs.com/package/@adobe/aep-rules-engine?

**Comment by dharmasagar** [comment]
@carterworks Thank you !

**Comment by carterworks** [comment]
> Hi @carterworks thank you for making this version bump,
> 
> ~do we have an estimate about how long it will take for us to see this new version on NPM https://www.npmjs.com/package/@adobe/aep-rules-engine?~
> 
> > We are in a company-wide restricted change period until January 5th, so unless an exception is made, expect this to be released after that period ends.
> 
> Got it, so it will be after Jan/05/2025

@alex-arriaga It has been released and is now available.

**Pull request merged**
